---

common_packages:
  - { name: acl, version: "2.3.2-1build1.1" }
  - { name: autoconf, version: "2.71-3" }
  - { name: build-essential, version: "12.10ubuntu1" }
  - { name: ca-certificates, version: "20240203" }
  - { name: curl, version: "8.5.0-2ubuntu10.6" }
  - { name: gnupg, version: "2.4.4-2ubuntu17.3" }
  - { name: jq, version: "1.7.1-3ubuntu0.24.04.1" }
  - { name: flex, version: "2.6.4-8.2build1" }
  - { name: kmod, version: "31+20240202-2ubuntu7.1" }
  - { name: libevent-dev, version: "2.1.12-stable-9ubuntu2" }
  - { name: libhwloc-dev, version: "2.10.0-1build1" }
  - { name: libjansson-dev, version: "2.14-2build2" }
  - { name: libjson-c-dev, version: "0.17-1build1" }
  - { name: liblz4-dev, version: "1.9.4-1build1.1" }
  - { name: libmunge-dev, version: "0.5.15-4build1" }
  - { name: libpam0g, version: "1.5.3-5ubuntu5.5" }
  - { name: libpam0g-dev, version: "1.5.3-5ubuntu5.5" }
  - { name: libssl-dev, version: "3.0.13-0ubuntu3.6" }
  - { name: libtool, version: "2.4.7-7build1" }
  - { name: libdrm-dev, version: "2.4.122-1~ubuntu0.24.04.1" }
  - { name: numactl, version: "2.0.18-1build1" }
  - { name: pkg-config, version: "1.8.1-2build1" }
  - { name: rdma-core, version: "50.0-2ubuntu0.2" }
  - { name: software-properties-common, version: "0.99.49.3" }
  - { name: squashfs-tools, version: "1:4.6.1-1build1" } # it's required for enroot
  - { name: sudo, version: "1.9.15p5-3ubuntu5.24.04.1" }
  - { name: infiniband-diags, version: "2404mlnx51-1.2404066" }
  - { name: ibverbs-utils, version: "50.0-2ubuntu0.2" }
  - { name: iproute2, version: "6.1.0-1ubuntu6.2" } # it's required for Slurm
  - { name: libdrm-dev, version: "2.4.122-1~ubuntu0.24.04.1" }
  - { name: libncurses-dev, version: "6.4+20240113-1ubuntu2" } # it's required for Slurm
  - { name: libpmix-dev, version: "5.0.1-4.1build1" }
  - { name: parallel, version: "20240222+ds-2" } # it's required for enroot operation
  - { name: time, version: "1.9-0.2build1" }
  - { name: wget, version: "1.21.4-1ubuntu4.1" }
  - { name: zstd, version: "1.5.5+dfsg2-2build1.1" } # it's required for enroot
  - { name: zip, version: "3.0-13ubuntu0.2" }
  - { name: unzip, version: "6.0-28ubuntu4.1" }
