apiVersion: v2
name: helm-nfs-server
description: A Helm chart for NFS server deployment
type: application
version: 1.22.2
appVersion: "1.22.2"
kubeVersion: ">=1.20.0-0"
keywords:
  - nfs
  - storage
  - filesystem
home: https://github.com/nebius/soperator
sources:
  - https://github.com/nebius/soperator/tree/main/images/nfs-server
maintainers:
  - name: Nebius Team
    email: support@nebius.com
