---

dpkg_arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: armhf

cuda_dpkg_arch_map:
  x86_64: x86_64
  aarch64: sbsa

libnccl_version: 2.26.5-1

packages_repo_url: "https://github.com/nebius/slurm-deb-packages/releases/download"
