# Usage of quote-wrapping for string literals in this example acts like a visual mark for referring to other resources
# like user-created PVCs or 3rd-party annotations

apiVersion: slurm.nebius.ai/v1
kind: SlurmCluster
metadata:
  namespace: dstaroff
  name: slurm1
spec:
  crVersion: 0.1.5
  pause: false
  periodicChecks:
    ncclBenchmark:
      suspend: false
      schedule: "0 */3 * * *" # Run every 3 hours
      activeDeadlineSeconds: 1800 # K8s CronJob timeout seconds (30 min)
      successfulJobsHistoryLimit: 3
      failedJobsHistoryLimit: 3
      image: cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/nccl_benchmark:latest
      ncclSettings:
        minBytes: "512Kb"
        maxBytes: "512Mb"
        stepFactor: "2"
        timeout: "20:00" # 20 minute
        thresholdMoreThan: "0"
      failureActions:
        #        setK8SNodeStatus: "GpuSlow"
        setSlurmNodeDrainState: "true"
      k8sNodeFilterName: "no-gpu-ssd"
  k8sNodeFilters:
    - name: gpu
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nebius.com/node-group-id"
                    operator: In
                    values:
                      - "f2m3qsrqa74ugs37saab"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
    - name: no-gpu-ssd
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nebius.com/node-group-id"
                    operator: In
                    values:
                      - "f2md1q6j5mq7mju9agk2"
  volumeSources:
    - name: controller-spool
      persistentVolumeClaim:
        claimName: "controller-spool"
        readOnly: false
    - name: jail
      persistentVolumeClaim:
        claimName: "jail"
        readOnly: false
    #- name: datasets
    #  persistentVolumeClaim:
    #    claimName: slurm-example-customer-datasets
    #    readOnly: false
    #- name: checkpoints
    #  persistentVolumeClaim:
    #    claimName: slurm-example-customer-checkpoints
    #    readOnly: false
    #- name: ml-config
    #  configMap:
    #    name: slurm-example-customer-ml-configs
  secrets:
    mungeKey:
      name: "munge-key"
      key: "munge.key"
    sshRootPublicKeys:
      name: "ssh-root-keys"
      keys:
        - "authorized_keys"
  slurmNodes:
    controller:
      size: 1
      k8sNodeFilterName: "no-gpu-ssd"
      slurmctld:
        image: "cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/controller_slurmctld:latest"
        port: 6817
        resources:
          cpu: 1000m
          memory: 10Gi
          ephemeralStorage: 10Gi
      munge:
        image: "cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/munge:latest"
      volumes:
        spool:
          volumeSourceName: "controller-spool"
        jail:
          volumeSourceName: "jail"
    worker:
      size: 1
      k8sNodeFilterName: "gpu"
      maxGpu: 1
      slurmd:
        image: "cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/worker_slurmd:latest"
        port: 6818
        resources:
          cpu: 1000m
          memory: 10Gi
          ephemeralStorage: 10Gi
      munge:
        image: "cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/munge:latest"
      volumes:
        spool:
          volumeClaimTemplateSpec:
            storageClassName: "nebius-network-ssd"
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
        jail:
          volumeSourceName: "jail"
        jailSubMounts: []
          #- name: datasets
          #  mountPath: "/mnt/datasets"
          #  volumeSourceName: "datasets"
          #- name: checkpoints
          #  mountPath: "/mnt/checkpoints"
          #  volumeSourceName: "checkpoints"
          #- name: ml-configs
          #  mountPath: "/etc/ml-config"
          #  volumeSourceName: "ml-configs"
    login:
      size: 1
      k8sNodeFilterName: "no-gpu-ssd"
      sshd:
        image: "cr.nemax.nebius.cloud/crnonjecps8pifr7am4i/login_sshd:latest"
        port: 22
        resources:
          cpu: 1000m
          memory: 10Gi
          ephemeralStorage: 10Gi
      sshdServiceType: "LoadBalancer"
      volumes:
        users:
          volumeClaimTemplateSpec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 10Gi
            storageClassName: "nebius-network-ssd"
            volumeMode: Filesystem
        jail:
          volumeSourceName: "jail"
        jailSubMounts: []
          #- name: "datasets"
          #  mountPath: "/mnt/datasets"
          #  volumeSourceName: "datasets"
          #- name: "checkpoints"
          #  mountPath: "/mnt/checkpoints"
          #  volumeSourceName: "checkpoints"
          #- name: "ml-configs"
          #  mountPath: "/etc/ml-config"
          #  volumeSourceName: "ml-configs"
