{{- if .Values.configMaps.motd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.motd.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "soperator-custom-configmaps.labels" . | nindent 4 }}
data:
  {{- range .Values.configMaps.motd.files }}
  {{ . }}: |
{{ tpl ($.Files.Get (printf "config-files/%s" .)) $ | indent 4 }}
  {{- end }}
{{- end }}
