{{- include "soperator-activechecks.checkReactionsConflict" (dict "name" "createUserSoperatorchecks" "vals" .Values) -}}
apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "create-user-soperatorchecks"
spec:
  checkType: "k8sJob"
  name: "create-user-soperatorchecks"
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: {{ .Values.checks.createUserSoperatorChecks.suspend }}
  runAfterCreation: {{ .Values.checks.createUserSoperatorChecks.runAfterCreation }}
  k8sJobSpec:
    jobContainer:
      command:
        - bash
        - -c
        - |
{{ .Files.Get "scripts/create-user-soperatorchecks.sh" | indent 10 }}
      image: {{ .Values.images.k8sJob | quote }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
