apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "cuda-samples"
spec:
  checkType: "slurmJob"
  name: "cuda-samples"
  dependsOn: [ "create-user-soperatorchecks", "wait-for-topology", "prepull-container-image" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "30 0-18/6 * * *" # 4 times a day at 00:30, 06:30, 12:30 and 18:30 UTC
  suspend: false
  runAfterCreation: true
  slurmJobSpec:
    sbatchScript: |
{{ tpl (.Files.Get "scripts/cuda-samples.sh") . | indent 6 }}
    eachWorkerJobs: true
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
  # Do not add any reactions right now, only monitor
  reactions:
    setCondition: false
    drainSlurmNode: false
    commentSlurmNode: true
