apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "cuda-samples"
spec:
  checkType: "slurmJob"
  name: "cuda-samples"
  dependsOn: [ "wait-for-soperatorchecks-srun-ready", "wait-for-topology", "prepull-container-image" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "30 0-18/6 * * *" # 4 times a day at 00:30, 06:30, 12:30 and 18:30 UTC
  suspend: {{ .Values.checks.cudaSamples.suspend }}
  runAfterCreation: {{ .Values.checks.cudaSamples.runAfterCreation }}
  slurmJobSpec:
    sbatchScript: |
{{ tpl (.Files.Get "scripts/cuda-samples.sh") . | indent 6 }}
    eachWorkerJobs: true
    jobContainer:
      appArmorProfile: unconfined
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
      appArmorProfile: unconfined
  failureReactions:
    drainSlurmNode:
      drainReasonPrefix: {{ .Values.checks.cudaSamples.drainReasonPrefix | quote }}
