apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "ib-gpu-perf"
spec:
  checkType: "slurmJob"
  name: "ib-gpu-perf"
  dependsOn: [ "wait-for-soperatorchecks-srun-ready", "wait-for-topology", "prepull-container-image" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "55 1-21/4 * * *" # 6 times a day at 01:55, 05:55, 09:55, 13:55, 17:55 and 21:55 UTC
  suspend: {{ .Values.checks.ibGpuPerf.suspend }}
  runAfterCreation: {{ .Values.checks.ibGpuPerf.runAfterCreation }}
  slurmJobSpec:
    sbatchScript: |
{{ tpl (.Files.Get "scripts/ib-gpu-perf.sh") . | indent 6 }}
    eachWorkerJobs: true
    maxNumberOfJobs: 200
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
  failureReactions:
    commentSlurmNode:
      commentPrefix: {{ .Values.checks.ibGpuPerf.commentPrefix | quote }}
