apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "ib-write-lat-cpu"
spec:
  checkType: "slurmJob"
  name: "ib-write-lat-cpu"
  dependsOn: [ "create-user-soperatorchecks", "wait-for-topology", "prepull-container-image" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "0 12 * * *" # 1 time a day at 12:00 UTC
  suspend: false
  runAfterCreation: true
  slurmJobSpec:
    sbatchScript: |
{{ .Files.Get "scripts/ib-write-lat-cpu.sh" | indent 6 }}
    eachWorkerJobs: true
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
  # Do not add any reactions right now, only monitor
  reactions:
    setCondition: false
    drainSlurmNode: false
    commentSlurmNode: true
