apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "mem-perf"
spec:
  checkType: "slurmJob"
  name: "mem-perf"
  dependsOn: [ "create-user-soperatorchecks", "wait-for-topology", "prepull-container-image" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  schedule: "20 10-22/12 * * *" # 2 times a day at 10:20 and 22:20 UTC
  suspend: {{ .Values.checks.memPerf.suspend }}
  runAfterCreation: {{ .Values.checks.memPerf.runAfterCreation }}
  slurmJobSpec:
    sbatchScript: |
{{ tpl (.Files.Get "scripts/mem-perf.sh") . | indent 6 }}
    eachWorkerJobs: true
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
  failureReactions:
    drainSlurmNode:
      drainReasonPrefix: {{ .Values.checks.memPerf.drainReasonPrefix }}
