{{- include "soperator-activechecks.checkReactionsConflict" (dict "comment" .Values.checks.prepullContainerImage.commentPrefix "drain" .Values.checks.prepullContainerImage.drainReasonPrefix "name" "checks.prepullContainerImage") -}}
apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "prepull-container-image"
spec:
  checkType: "slurmJob"
  name: "prepull-container-image"
  dependsOn: [ "wait-for-soperatorchecks-srun-ready", "wait-for-topology" ]
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: {{ .Values.checks.prepullContainerImage.suspend }}
  runAfterCreation: {{ .Values.checks.prepullContainerImage.runAfterCreation }}
  slurmJobSpec:
    sbatchScript: |
{{ tpl (.Files.Get "scripts/prepull-container-image.sh") . | indent 6 }}
    jobContainer:
      image: {{ .Values.images.slurmJob | quote }}
      env:
{{ toYaml .Values.jobContainer.env | indent 8 }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
    mungeContainer:
      image: {{ .Values.images.munge | quote }}
