apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "retrigger-checks"
spec:
  checkType: "k8sJob"
  name: "retrigger-checks"
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: true
  runAfterCreation: false
  k8sJobSpec:
    jobContainer:
      command:
        - bash
        - -c
        - |
          python3 - <<'PY'
{{ .Files.Get "scripts/retrigger-checks.py" | indent 10 }}
          PY
      image: {{ .Values.images.k8sJob | quote }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
