{{- include "soperator-activechecks.checkReactionsConflict" (dict "comment" .Values.checks.soperatorOutputsLogsCleaner.commentPrefix "drain" .Values.checks.soperatorOutputsLogsCleaner.drainReasonPrefix "name" "checks.soperatorOutputsLogsCleaner") -}}
apiVersion: slurm.nebius.ai/v1alpha1
kind: ActiveCheck
metadata:
  name: "soperator-outputs-logs-cleaner"
spec:
  checkType: "k8sJob"
  schedule: "40 */1 * * *" # At the 40th minute of every hour
  name: "soperator-outputs-logs-cleaner"
  slurmClusterRefName: {{ .Values.slurmClusterRefName | quote }}
  suspend: {{ .Values.checks.soperatorOutputsLogsCleaner.suspend }}
  runAfterCreation: {{ .Values.checks.soperatorOutputsLogsCleaner.runAfterCreation }}
  k8sJobSpec:
    jobContainer:
      command:
        - bash
        - -c
        - |
{{ .Files.Get "scripts/soperator-outputs-logs-cleaner.sh" | indent 10 }}
      image: {{ .Values.images.k8sJob | quote }}
      volumeMounts:
{{ toYaml .Values.jobContainer.volumeMounts | indent 8 }}
      volumes:
{{ toYaml .Values.jobContainer.volumes | indent 8 }}
