{{- if and .Values.slurmNodes.exporter.enabled .Values.slurmNodes.exporter.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "slurm-cluster.exporter.roleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurm-exporter
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
{{- end }}
