{{- if and .Values.slurmNodes.exporter.enabled .Values.slurmNodes.exporter.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slurm-cluster.exporter.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurm-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slurm-cluster.exporter.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "slurm-cluster.exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
