{{- if .Values.sConfigController.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slurm-cluster.sconfigcontroller.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: sconfigcontroller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slurm-cluster.sconfigcontroller.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "slurm-cluster.sconfigcontroller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
