{{- if .Values.sConfigController.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-cluster.sconfigcontroller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: sconfigcontroller
{{- end }}
