{{- if .Values.slurmNodes.controller.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "slurm-cluster.controller.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: slurm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "slurm-cluster.controller.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "slurm-cluster.controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
