apiVersion: v2
name: helm-soperator
description: A Helm chart for Kubernetes
type: application
version: 3.0.0
appVersion: "3.0.0"
kubeVersion: ">=1.29.0-0"
dependencies:
  - name: kruise
    version: 1.8.0
    repository: https://openkruise.github.io/charts/
    condition: kruise.installOperator
