apiVersion: v2
name: helm-soperator
description: A Helm chart for Kubernetes
type: application
version: 1.22.4
appVersion: "1.22.4"
kubeVersion: ">=1.29.0-0"
dependencies:
  - name: kruise
    version: 1.8.0
    repository: https://openkruise.github.io/charts/
    condition: kruise.installOperator
