---

- name: Ensure docker-cli package is installed
  ansible.builtin.apt:
    name:
      - "docker-ce-cli={{ docker_cli_version }}"
  tags:
    - docker-cli

- name: Move real docker binary out of the way
  ansible.builtin.command: mv /usr/bin/docker /usr/bin/docker.real
  args:
    creates: /usr/bin/docker.real
  tags:
    - docker-cli

- name: Install docker wrapper script
  ansible.builtin.copy:
    src: docker.sh
    dest: /usr/bin/docker
    owner: root
    group: root
    mode: "0755"
  tags:
    - docker-cli
