provisioners: []

diskTypes: []

fsTypes: []

reclaimPolicy: Delete

volumeBindingMode: WaitForFirstConsumer

allowVolumeExpansion: false

annotations: {}

labels: {}

mountOptions: []

parameters: {}
