activeCheck:
  enabled: true
  suspend: false
  name: "clear-enroot-check"
  checkType: "slurmJob"
  schedule: "0 0 * * *"    # every 24 hours
  slurmJobSpec:
    eachWorkerJobArray: true
    sbatchScript: |
      #!/bin/bash
      #SBATCH --deadline="now+12hours"
      #SBATCH --time=1:00:00
      #SBATCH --exclusive
      #SBATCH --output=/opt/soperatorchecks/%N.%x.%j.%A.out
      #SBATCH --error=/opt/soperatorchecks/%N.%x.%j.%A.out

      echo "Cleaning up Enroot containers on node: $(hostname)"
      srun bash -c "enroot list | grep '^pyxis_' | xargs -r -n1 enroot remove --force"
      echo "Cleanup done."
